CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256) NULL,
        "NormalizedName" character varying(256) NULL,
        "ConcurrencyStamp" text NULL,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "UserName" character varying(256) NULL,
        "NormalizedUserName" character varying(256) NULL,
        "Email" character varying(256) NULL,
        "NormalizedEmail" character varying(256) NULL,
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text NULL,
        "SecurityStamp" text NULL,
        "ConcurrencyStamp" text NULL,
        "PhoneNumber" text NULL,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone NULL,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        "IsEnabled" boolean NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE TABLE "Categories" (
        "CategoryId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text NOT NULL,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("CategoryId")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE TABLE "Geographies" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        CONSTRAINT "PK_Geographies" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE TABLE "Provinces" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Code" text NOT NULL,
        "Name_th" text NOT NULL,
        "Name_en" text NOT NULL,
        "Geography_id" integer NOT NULL,
        CONSTRAINT "PK_Provinces" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text NULL,
        "ClaimValue" text NULL,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text NULL,
        "ClaimValue" text NULL,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text NULL,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text NULL,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE TABLE "Products" (
        "ProductId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Amount" integer NOT NULL,
        "Price" numeric NOT NULL,
        "CategoryId" integer NOT NULL,
        "ProductImage" text NULL,
        CONSTRAINT "PK_Products" PRIMARY KEY ("ProductId"),
        CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("CategoryId") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE TABLE "Aumphures" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Code" text NOT NULL,
        "Name_th" text NOT NULL,
        "Name_en" text NOT NULL,
        "Province_id" integer NOT NULL,
        CONSTRAINT "PK_Aumphures" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Aumphures_Provinces_Province_id" FOREIGN KEY ("Province_id") REFERENCES "Provinces" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE TABLE "Orderings" (
        "OrderingId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NULL,
        "ProductId" integer NOT NULL,
        "Payment" integer NOT NULL,
        "Status" integer NOT NULL,
        "Discount" numeric NULL,
        "Amount" integer NOT NULL,
        "TotalPrice" numeric NULL,
        "Time" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_Orderings" PRIMARY KEY ("OrderingId"),
        CONSTRAINT "FK_Orderings_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("ProductId") ON DELETE CASCADE,
        CONSTRAINT "FK_Orderings_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE TABLE "Districts" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Zip_code" integer NOT NULL,
        "Name_th" text NOT NULL,
        "Name_en" text NOT NULL,
        "Aumphure_id" integer NOT NULL,
        CONSTRAINT "PK_Districts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Districts_Aumphures_Aumphure_id" FOREIGN KEY ("Aumphure_id") REFERENCES "Aumphures" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE TABLE "Receivers" (
        "ReceiverId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Lastname" text NOT NULL,
        "Tel" text NOT NULL,
        "Address" text NOT NULL,
        "District_id" integer NOT NULL,
        "Aumphure_id" integer NOT NULL,
        "Province_id" integer NOT NULL,
        "OrderingId" integer NOT NULL,
        CONSTRAINT "PK_Receivers" PRIMARY KEY ("ReceiverId"),
        CONSTRAINT "FK_Receivers_Aumphures_Aumphure_id" FOREIGN KEY ("Aumphure_id") REFERENCES "Aumphures" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Receivers_Districts_District_id" FOREIGN KEY ("District_id") REFERENCES "Districts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Receivers_Orderings_OrderingId" FOREIGN KEY ("OrderingId") REFERENCES "Orderings" ("OrderingId") ON DELETE CASCADE,
        CONSTRAINT "FK_Receivers_Provinces_Province_id" FOREIGN KEY ("Province_id") REFERENCES "Provinces" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE TABLE "UserDetails" (
        "UserDetailId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "Tel" text NOT NULL,
        "Address" text NOT NULL,
        "District_id" integer NOT NULL,
        "Aumphure_id" integer NOT NULL,
        "Province_id" integer NOT NULL,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_UserDetails" PRIMARY KEY ("UserDetailId"),
        CONSTRAINT "FK_UserDetails_Aumphures_Aumphure_id" FOREIGN KEY ("Aumphure_id") REFERENCES "Aumphures" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserDetails_Districts_District_id" FOREIGN KEY ("District_id") REFERENCES "Districts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserDetails_Provinces_Province_id" FOREIGN KEY ("Province_id") REFERENCES "Provinces" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserDetails_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE INDEX "IX_Aumphures_Province_id" ON "Aumphures" ("Province_id");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE INDEX "IX_Districts_Aumphure_id" ON "Districts" ("Aumphure_id");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE INDEX "IX_Orderings_ProductId" ON "Orderings" ("ProductId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE INDEX "IX_Orderings_UserId" ON "Orderings" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE INDEX "IX_Receivers_Aumphure_id" ON "Receivers" ("Aumphure_id");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE INDEX "IX_Receivers_District_id" ON "Receivers" ("District_id");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE UNIQUE INDEX "IX_Receivers_OrderingId" ON "Receivers" ("OrderingId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE INDEX "IX_Receivers_Province_id" ON "Receivers" ("Province_id");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE INDEX "IX_UserDetails_Aumphure_id" ON "UserDetails" ("Aumphure_id");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE INDEX "IX_UserDetails_District_id" ON "UserDetails" ("District_id");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE INDEX "IX_UserDetails_Province_id" ON "UserDetails" ("Province_id");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    CREATE UNIQUE INDEX "IX_UserDetails_UserId" ON "UserDetails" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200710071539_first') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200710071539_first', '3.1.3');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200722112515_StringTostring') THEN
    ALTER TABLE "UserDetails" DROP CONSTRAINT "FK_UserDetails_AspNetUsers_UserId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200722112515_StringTostring') THEN
    ALTER TABLE "UserDetails" ALTER COLUMN "UserId" TYPE text;
    ALTER TABLE "UserDetails" ALTER COLUMN "UserId" DROP NOT NULL;
    ALTER TABLE "UserDetails" ALTER COLUMN "UserId" DROP DEFAULT;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200722112515_StringTostring') THEN
    ALTER TABLE "UserDetails" ADD CONSTRAINT "FK_UserDetails_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200722112515_StringTostring') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200722112515_StringTostring', '3.1.3');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803062115_AddforeignkeyCancleUserId') THEN
    ALTER TABLE "Orderings" DROP CONSTRAINT "FK_Orderings_AspNetUsers_UserId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803062115_AddforeignkeyCancleUserId') THEN
    DROP INDEX "IX_Orderings_UserId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803062115_AddforeignkeyCancleUserId') THEN
    ALTER TABLE "Orderings" ADD "CancelUserId" text NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803062115_AddforeignkeyCancleUserId') THEN
    CREATE INDEX "IX_Orderings_CancelUserId" ON "Orderings" ("CancelUserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803062115_AddforeignkeyCancleUserId') THEN
    ALTER TABLE "Orderings" ADD CONSTRAINT "FK_Orderings_AspNetUsers_CancelUserId" FOREIGN KEY ("CancelUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803062115_AddforeignkeyCancleUserId') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200803062115_AddforeignkeyCancleUserId', '3.1.3');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803073409_AddForeignkey2') THEN
    CREATE INDEX "IX_Orderings_UserId" ON "Orderings" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803073409_AddForeignkey2') THEN
    ALTER TABLE "Orderings" ADD CONSTRAINT "FK_Orderings_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803073409_AddForeignkey2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200803073409_AddForeignkey2', '3.1.3');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200812045250_UserImage') THEN
    ALTER TABLE "AspNetUsers" ADD "UserImage" text NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200812045250_UserImage') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200812045250_UserImage', '3.1.3');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200813041753_EditUserImage') THEN
    ALTER TABLE "AspNetUsers" DROP COLUMN "UserImage";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200813041753_EditUserImage') THEN
    ALTER TABLE "UserDetails" ADD "UserImage" text NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200813041753_EditUserImage') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200813041753_EditUserImage', '3.1.3');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200817085913_testMaxLenge') THEN
    ALTER TABLE "Receivers" ALTER COLUMN "Name" TYPE character varying(20);
    ALTER TABLE "Receivers" ALTER COLUMN "Name" SET NOT NULL;
    ALTER TABLE "Receivers" ALTER COLUMN "Name" DROP DEFAULT;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200817085913_testMaxLenge') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200817085913_testMaxLenge', '3.1.3');
    END IF;
END $$;
